	server{
		#listen 80;

		listen 443 ssl http2;

		ssl_certificate /etc/letsencrypt/live/abhiyanlimbu.com.np/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/abhiyanlimbu.com.np/privkey.pem;
		ssl_protocols TLSv1.2 TLSv1.3;
		
		server_name abhiyanlimbu.com.np www.abhiyanlimbu.com.np;
		root /var/www/html/portfolio-web/;
		index index.html;

		location /{
			try_files $uri $uri/ = 404;
		}

		access_log /var/log/nginx/portfolio-web.access.log;
		error_log /var/log/nginx/portfolio-web.error.log;
	}


